Added history popup component and code for it
BloomTech-Labs/family-promise-case-mgmt-fe pull request #54
Opened 2022-09-21 20:28 UTC by jacob-bro

This will add the component needed for the history pop up window to function. Nothing is changed except to add the component file.
https://www.loom.com/share/c17e5924d0e44d829b53bb039ad6cbac

2022-09-21 23:09 UTC, ChrisJRamirez reviewed
For the most part the code looks good, I am just seeing a message in the review that says "React Hook useEffect has a missing dependency: 'options'. Either include it or remove the dependency array" and it is referencing line 27 on the client intake form. This may be out of the scope for this branch/task.

2022-09-26 22:42 UTC, ashtilawat23 requested changes
Could you convert this to a functional component? If we could move forward with the ant-design modal instead, that would be awesome! The `react-modal-resizable-draggle` hasn't been maintained or updated since 2021.

2022-09-26 22:42 UTC, ashtilawat23 commented on src/components/common/HistoryPopup.js
> +import ReactModal from "react-modal-resizable-draggable";
Any reason we couldn't use the ant-design model here? https://ant.design/components/modal/
Looks like you added a brand new dependency

2022-09-26 22:42 UTC, ashtilawat23 commented on src/components/common/HistoryPopup.js
> +class Popup extends Component {
Could you do a functional component instead? There are no other class components in the app

2022-11-04 16:04 UTC, merged